import type { ExtendedOverlayConfig, TemplateId } from '../core/types';

/** Default template configurations */
export const TEMPLATE_CONFIGS: Record<TemplateId, ExtendedOverlayConfig> = {
  'minimalist': {
    templateId: 'minimalist',
    position: 'top-right',
    backgroundOpacity: 0.5,
    fontSizePercent: 2.0,
    showHr: true,
    showPace: true,
    showDistance: true,
    showTime: true,
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    textColor: '#FFFFFF',
    backgroundColor: '#000000',
    borderWidth: 0,
    borderColor: '#FFFFFF',
    cornerRadius: 4,
    textShadow: false,
    textShadowColor: '#000000',
    textShadowBlur: 2,
    lineSpacing: 1.2,
    layout: 'vertical',
    iconStyle: 'outline',
    gradientBackground: false,
    gradientStartColor: '#000000',
    gradientEndColor: '#333333',
  },
  
  'sporty': {
    templateId: 'sporty',
    position: 'bottom-right',
    backgroundOpacity: 0.8,
    fontSizePercent: 2.8,
    showHr: true,
    showPace: true,
    showDistance: true,
    showTime: true,
    fontFamily: '"Helvetica Neue", Arial, sans-serif',
    textColor: '#FF4136', // Red for emphasis
    backgroundColor: '#000000',
    borderWidth: 2,
    borderColor: '#FF4136',
    cornerRadius: 8,
    textShadow: true,
    textShadowColor: '#000000',
    textShadowBlur: 3,
    lineSpacing: 1.4,
    layout: 'vertical',
    iconStyle: 'filled',
    gradientBackground: true,
    gradientStartColor: '#000000',
    gradientEndColor: '#444444',
  },
  
  'professional': {
    templateId: 'professional',
    position: 'top-left',
    backgroundOpacity: 0.7,
    fontSizePercent: 2.2,
    showHr: true,
    showPace: true,
    showDistance: true,
    showTime: true,
    fontFamily: 'Georgia, "Times New Roman", serif',
    textColor: '#FFFFFF',
    backgroundColor: '#1A1A1A',
    borderWidth: 1,
    borderColor: '#CCCCCC',
    cornerRadius: 6,
    textShadow: false,
    textShadowColor: '#000000',
    textShadowBlur: 1,
    lineSpacing: 1.3,
    layout: 'vertical',
    iconStyle: 'none',
    gradientBackground: false,
    gradientStartColor: '#1A1A1A',
    gradientEndColor: '#3A3A3A',
  },
  
  'modern': {
    templateId: 'modern',
    position: 'bottom-left',
    backgroundOpacity: 0.6,
    fontSizePercent: 2.5,
    showHr: true,
    showPace: true,
    showDistance: true,
    showTime: true,
    fontFamily: 'system-ui, -apple-system, sans-serif',
    textColor: '#0074D9', // Blue for modern feel
    backgroundColor: '#F8F9FA',
    borderWidth: 0,
    borderColor: '#0074D9',
    cornerRadius: 12,
    textShadow: false,
    textShadowColor: '#000000',
    textShadowBlur: 1,
    lineSpacing: 1.5,
    layout: 'vertical',
    iconStyle: 'filled',
    gradientBackground: true,
    gradientStartColor: '#F8F9FA',
    gradientEndColor: '#E9ECEF',
  },
  
  'high-contrast': {
    templateId: 'high-contrast',
    position: 'bottom-right',
    backgroundOpacity: 0.9,
    fontSizePercent: 3.0,
    showHr: true,
    showPace: true,
    showDistance: true,
    showTime: true,
    fontFamily: 'Arial Black, Arial, sans-serif',
    textColor: '#FFFF00', // Yellow for high contrast
    backgroundColor: '#000000',
    borderWidth: 3,
    borderColor: '#FFFF00',
    cornerRadius: 4,
    textShadow: false,
    textShadowColor: '#000000',
    textShadowBlur: 0,
    lineSpacing: 1.1,
    layout: 'vertical',
    iconStyle: 'filled',
    gradientBackground: false,
    gradientStartColor: '#000000',
    gradientEndColor: '#333333',
  },
  
  'custom': {
    templateId: 'custom',
    position: 'top-left',
    backgroundOpacity: 0.7,
    fontSizePercent: 2.5,
    showHr: true,
    showPace: true,
    showDistance: true,
    showTime: true,
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    textColor: '#FFFFFF',
    backgroundColor: '#000000',
    borderWidth: 0,
    borderColor: '#FFFFFF',
    cornerRadius: 4,
    textShadow: false,
    textShadowColor: '#000000',
    textShadowBlur: 2,
    lineSpacing: 1.5,
    layout: 'vertical',
    iconStyle: 'outline',
    gradientBackground: false,
    gradientStartColor: '#000000',
    gradientEndColor: '#333333',
  }
};

/** Get a template configuration by ID */
export function getTemplateConfig(templateId: TemplateId): ExtendedOverlayConfig {
  return { ...TEMPLATE_CONFIGS[templateId] };
}

/** Get all available template IDs */
export function getAvailableTemplates(): TemplateId[] {
  return Object.keys(TEMPLATE_CONFIGS) as TemplateId[];
}