import type { TemplateDefinition } from './types';

export const arcGaugeTemplate: TemplateDefinition = {
    id: 'arc-gauge',
    metadata: {
        id: 'arc-gauge',
        name: 'Arc Gauge',
        description: 'Pace-focused arc gauge with secondary side metrics',
        previewColors: { bg: '#0a0f1f', accent: '#ffffff', text: '#e5e7eb' },
    },
    config: {
        templateId: 'arc-gauge',
        layoutMode: 'arc-gauge',
        position: 'top-left',
        backgroundOpacity: 0,
        fontSizePercent: 2.2,
        showHr: true,
        showPace: true,
        showDistance: true,
        showTime: true,
        fontFamily: 'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
        textColor: '#FFFFFF',
        backgroundColor: 'transparent',
        borderWidth: 0,
        borderColor: 'transparent',
        cornerRadius: 0,
        textShadow: true,
        textShadowColor: 'rgba(0,0,0,0.45)',
        textShadowBlur: 6,
        lineSpacing: 1.1,
        layout: 'horizontal',
        iconStyle: 'none',
        gradientBackground: false,
        gradientStartColor: '#000000',
        gradientEndColor: '#333333',
        labelStyle: 'uppercase',
        valueFontWeight: 'light',
        valueSizeMultiplier: 1.8,
        labelSizeMultiplier: 0.45,
        labelLetterSpacing: 0.18,
        accentColor: '#ffffff',
    },
};
