import type { TemplateDefinition } from './types';

export const cinematicBarTemplate: TemplateDefinition = {
  id: 'cinematic-bar',
  metadata: {
    id: 'cinematic-bar',
    name: 'Cinematic Bar',
    description: 'Letterbox bars with compact bottom telemetry strip',
    previewColors: { bg: '#000000', accent: '#ffffff', text: '#f8fafc' },
  },
  config: {
    templateId: 'cinematic-bar',
    layoutMode: 'cinematic-bar',
    position: 'bottom-left',
    backgroundOpacity: 0.6,
    fontSizePercent: 1.85,
    showHr: true,
    showPace: true,
    showDistance: true,
    showTime: true,
    fontFamily: 'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    textColor: '#FFFFFF',
    backgroundColor: '#000000',
    borderWidth: 0,
    borderColor: 'transparent',
    cornerRadius: 0,
    textShadow: false,
    textShadowColor: '#000000',
    textShadowBlur: 0,
    lineSpacing: 1.15,
    layout: 'horizontal',
    iconStyle: 'none',
    gradientBackground: false,
    gradientStartColor: '#000000',
    gradientEndColor: '#333333',
    labelStyle: 'uppercase',
    valueFontWeight: 'normal',
    valueSizeMultiplier: 1.05,
    labelSizeMultiplier: 0.42,
    labelLetterSpacing: 0.16,
    accentColor: '#FFFFFF',
  },
};
