import { DEFAULT_CAPABILITIES, defineTemplate } from './types';

export const cockpitHudTemplate = defineTemplate({
  id: 'cockpit-hud',
  metadata: {
    name: 'Cockpit HUD',
    description: 'Structured motorsport-inspired HUD with disciplined grid, modern typography, and balanced telemetry blocks',
    previewColors: { bg: '#08111d', accent: '#ff7a1a', text: '#f4f7fb' },
  },
  config: {
    layoutMode: 'cockpit-hud',
    position: 'bottom-left',
    backgroundOpacity: 0.9,
    fontSizePercent: 2.2,
    fontFamily: 'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    textColor: '#FFFFFF',
    backgroundColor: '#080d14',
    textShadow: true,
    textShadowColor: 'rgba(0,0,0,0.82)',
    textShadowBlur: 2,
    lineSpacing: 1.15,
    layout: 'horizontal',
    labelStyle: 'uppercase',
    valueFontWeight: 'bold',
    valueSizeMultiplier: 1.5,
    labelSizeMultiplier: 0.46,
    labelLetterSpacing: 0.08,
    accentColor: '#ff7a1a',
  },
  capabilities: {
    ...DEFAULT_CAPABILITIES,
    supportedMetrics: ['pace', 'hr', 'distance', 'time', 'power'],
    supportsPosition: false,
    supportsBackgroundOpacity: true,
    supportsGradient: false,
    supportsBorder: false,
    supportsTextShadow: true,
    supportsLayoutDirection: false,
  },
  styles: {
    typography: {
      fontFamily: 'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      valueFontWeight: 'bold',
      labelFontWeight: 'normal',
      valueSizeMultiplier: 1.5,
      labelSizeMultiplier: 0.46,
      labelLetterSpacing: 0.08,
    },
    spacing: {
      basePaddingPercent: 0.03,
      metricGapPercent: 0.015,
      lineSpacing: 1.15,
    },
    visual: {
      textShadow: true,
      textShadowBlur: 2,
      labelStyle: 'uppercase',
    },
  },
});
