import type { TemplateDefinition } from './types';

export const cockpitHudTemplate: TemplateDefinition = {
    id: 'cockpit-hud',
    metadata: {
        id: 'cockpit-hud',
        name: 'Cockpit HUD',
        description: 'Full cockpit: large pace left, waveform HR bar right, distance center, orange divider line',
        previewColors: { bg: '#0a0a0a', accent: '#f97316', text: '#e5e7eb' },
    },
    config: {
        templateId: 'cockpit-hud',
        layoutMode: 'cockpit-hud',
        position: 'bottom-left',
        backgroundOpacity: 0,
        fontSizePercent: 2.4,
        showHr: true,
        showPace: true,
        showDistance: true,
        showTime: true,
        fontFamily: '"JetBrains Mono", "Fira Code", monospace',
        textColor: '#FFFFFF',
        backgroundColor: 'transparent',
        borderWidth: 0,
        borderColor: 'transparent',
        cornerRadius: 0,
        textShadow: false,
        textShadowColor: 'rgba(0,0,0,0.4)',
        textShadowBlur: 0,
        lineSpacing: 1.0,
        layout: 'horizontal',
        iconStyle: 'none',
        gradientBackground: false,
        gradientStartColor: '#000000',
        gradientEndColor: '#000000',
        labelStyle: 'uppercase',
        valueFontWeight: 'light',
        valueSizeMultiplier: 2.0,
        labelSizeMultiplier: 0.35,
        labelLetterSpacing: 0.25,
        accentColor: '#f97316',
    },
};
