import type { TemplateDefinition } from './types';
import { DEFAULT_CAPABILITIES } from './types';

export const cockpitHudTemplate: TemplateDefinition = {
    id: 'cockpit-hud',
    metadata: {
        id: 'cockpit-hud',
        name: 'Cockpit HUD',
      description: 'Structured motorsport-inspired HUD with disciplined grid, modern typography, and balanced telemetry blocks',
      previewColors: { bg: '#08111d', accent: '#ff7a1a', text: '#f4f7fb' },
    },
    config: {
        templateId: 'cockpit-hud',
        layoutMode: 'cockpit-hud',
        position: 'bottom-left',
        backgroundOpacity: 0,
        fontSizePercent: 2.4,
        showHr: true,
        showPace: true,
        showDistance: true,
        showTime: true,
        fontFamily: '"Inter Tight", Inter, "SF Pro Display", -apple-system, BlinkMacSystemFont, sans-serif',
        textColor: '#FFFFFF',
        backgroundColor: 'transparent',
        borderWidth: 0,
        borderColor: 'transparent',
        cornerRadius: 0,
        textShadow: false,
        textShadowColor: 'rgba(0,0,0,0.4)',
        textShadowBlur: 0,
        lineSpacing: 1.0,
        layout: 'horizontal',
        iconStyle: 'none',
        gradientBackground: false,
        gradientStartColor: '#000000',
        gradientEndColor: '#000000',
        labelStyle: 'uppercase',
        valueFontWeight: 'bold',
        valueSizeMultiplier: 1.85,
        labelSizeMultiplier: 0.34,
        labelLetterSpacing: 0.18,
        accentColor: '#ff7a1a',
    },
  capabilities: {
    ...DEFAULT_CAPABILITIES,
    supportedMetrics: ['pace', 'hr', 'distance', 'time'],
    requiredMetrics: [],
    supportsPosition: false,
    supportsBackgroundOpacity: true,
    supportsGradient: false,
    supportsBorder: false,
    supportsTextShadow: true,
    supportsAccentColor: true,
    supportsLayoutDirection: false,
  },
  styles: {
    typography: {
      fontFamily: 'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      valueFontWeight: 'normal',
      labelFontWeight: 'normal',
      valueSizeMultiplier: 2.0,
      labelSizeMultiplier: 0.4,
      labelLetterSpacing: 0.1,
    },
    spacing: {
      basePaddingPercent: 0.02,
      metricGapPercent: 0.01,
      lineSpacing: 1.2,
    },
    visual: {
      cornerRadius: 0,
      borderWidth: 0,
      textShadow: false,
      textShadowBlur: 0,
      iconStyle: 'none',
      labelStyle: 'uppercase',
    },
  },
};
