import type { TemplateDefinition } from './types';
import { DEFAULT_CAPABILITIES } from './types';

export const condensedStripTemplate: TemplateDefinition = {
    id: 'condensed-strip',
    metadata: {
        id: 'condensed-strip',
        name: 'Condensed Strip',
        description: 'Dense horizontal strip for compact telemetry',
        previewColors: { bg: '#ffffff', accent: '#111111', text: '#111111' },
    },
    config: {
        templateId: 'condensed-strip',
        layoutMode: 'condensed-strip',
        position: 'bottom-left',
        backgroundOpacity: 1,
        fontSizePercent: 1.75,
        showHr: true,
        showPace: true,
        showDistance: true,
        showTime: true,
        fontFamily: '"Arial Narrow", "Helvetica Neue", Arial, sans-serif',
        textColor: '#111111',
        backgroundColor: '#FFFFFF',
        borderWidth: 0,
        borderColor: 'transparent',
        cornerRadius: 0,
        textShadow: false,
        textShadowColor: '#000000',
        textShadowBlur: 0,
        lineSpacing: 1,
        layout: 'horizontal',
        iconStyle: 'none',
        gradientBackground: false,
        gradientStartColor: '#ffffff',
        gradientEndColor: '#ffffff',
        labelStyle: 'uppercase',
        valueFontWeight: 'bold',
        valueSizeMultiplier: 1.15,
        labelSizeMultiplier: 0.45,
        labelLetterSpacing: 0.08,
        accentColor: '#111111',
    },
  capabilities: {
    ...DEFAULT_CAPABILITIES,
    supportedMetrics: ['pace', 'hr', 'distance', 'time'],
    requiredMetrics: [],
    supportsPosition: false,
    supportsBackgroundOpacity: true,
    supportsGradient: false,
    supportsBorder: false,
    supportsTextShadow: true,
    supportsAccentColor: true,
    supportsLayoutDirection: false,
  },
  styles: {
    typography: {
      fontFamily: 'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      valueFontWeight: 'normal',
      labelFontWeight: 'normal',
      valueSizeMultiplier: 2.0,
      labelSizeMultiplier: 0.4,
      labelLetterSpacing: 0.1,
    },
    spacing: {
      basePaddingPercent: 0.02,
      metricGapPercent: 0.01,
      lineSpacing: 1.2,
    },
    visual: {
      cornerRadius: 0,
      borderWidth: 0,
      textShadow: false,
      textShadowBlur: 0,
      iconStyle: 'none',
      labelStyle: 'uppercase',
    },
  },
};
