import type { TemplateDefinition } from './types';

export const condensedStripTemplate: TemplateDefinition = {
    id: 'condensed-strip',
    metadata: {
        id: 'condensed-strip',
        name: 'Condensed Strip',
        description: 'Dense horizontal strip for compact telemetry',
        previewColors: { bg: '#ffffff', accent: '#111111', text: '#111111' },
    },
    config: {
        templateId: 'condensed-strip',
        layoutMode: 'condensed-strip',
        position: 'bottom-left',
        backgroundOpacity: 1,
        fontSizePercent: 1.75,
        showHr: true,
        showPace: true,
        showDistance: true,
        showTime: true,
        fontFamily: '"Arial Narrow", "Helvetica Neue", Arial, sans-serif',
        textColor: '#111111',
        backgroundColor: '#FFFFFF',
        borderWidth: 0,
        borderColor: 'transparent',
        cornerRadius: 0,
        textShadow: false,
        textShadowColor: '#000000',
        textShadowBlur: 0,
        lineSpacing: 1,
        layout: 'horizontal',
        iconStyle: 'none',
        gradientBackground: false,
        gradientStartColor: '#ffffff',
        gradientEndColor: '#ffffff',
        labelStyle: 'uppercase',
        valueFontWeight: 'bold',
        valueSizeMultiplier: 1.15,
        labelSizeMultiplier: 0.45,
        labelLetterSpacing: 0.08,
        accentColor: '#111111',
    },
};
