import { DEFAULT_CAPABILITIES, defineTemplate } from './types';

export const cyclingProTemplate = defineTemplate({
    id: 'cycling-pro',
    metadata: {
        name: 'Cycling Pro',
        description: 'Velomobile-inspired HUD with live drivetrain metrics and a speed dial',
        previewColors: { bg: '#060606', accent: '#00E676', text: '#FFFFFF' },
    },
    config: {
        layoutMode: 'cycling-pro',
        position: 'bottom-left',
        backgroundOpacity: 0,
        fontSizePercent: 2.2,
        showHr: true,
        showPace: false,
        showDistance: true,
        showTime: false,
        showSpeed: true,
        showGrade: false,
        showElevation: false,
        showCadence: true,
        showPower: true,
        fontFamily: 'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
        textColor: '#FFFFFF',
        backgroundColor: 'transparent',
        borderWidth: 0,
        borderColor: 'transparent',
        cornerRadius: 0,
        textShadow: true,
        textShadowColor: 'rgba(0,0,0,0.9)',
        textShadowBlur: 6,
        lineSpacing: 1,
        layout: 'vertical',
        iconStyle: 'none',
        gradientBackground: false,
        gradientStartColor: 'transparent',
        gradientEndColor: 'transparent',
        labelStyle: 'uppercase',
        valueFontWeight: 'normal',
        valueSizeMultiplier: 2.1,
        labelSizeMultiplier: 0.32,
        labelLetterSpacing: 0.05,
        accentColor: '#00E676',
    },
    capabilities: {
        ...DEFAULT_CAPABILITIES,
        supportedMetrics: ['hr', 'cadence', 'power', 'speed', 'distance'],
        requiredMetrics: ['speed', 'distance'],
        supportsPosition: false,
        supportsBackgroundOpacity: false,
        supportsGradient: false,
        supportsBorder: false,
        supportsTextShadow: true,
        supportsAccentColor: false,
        supportsLayoutDirection: false,
    },
});
