import type { TemplateDefinition } from './types';

export const dashboardHudTemplate: TemplateDefinition = {
    id: 'dashboard-hud',
    metadata: {
        id: 'dashboard-hud',
        name: 'Dashboard HUD',
        description: 'Cockpit-inspired split telemetry HUD',
        previewColors: { bg: '#091016', accent: '#ef4444', text: '#e2e8f0' },
    },
    config: {
        templateId: 'dashboard-hud',
        layoutMode: 'dashboard-hud',
        position: 'top-left',
        backgroundOpacity: 0,
        fontSizePercent: 2.0,
        showHr: true,
        showPace: true,
        showDistance: true,
        showTime: true,
        fontFamily: 'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
        textColor: '#FFFFFF',
        backgroundColor: 'transparent',
        borderWidth: 0,
        borderColor: 'transparent',
        cornerRadius: 0,
        textShadow: true,
        textShadowColor: 'rgba(0,0,0,0.55)',
        textShadowBlur: 5,
        lineSpacing: 1.2,
        layout: 'horizontal',
        iconStyle: 'none',
        gradientBackground: false,
        gradientStartColor: '#000000',
        gradientEndColor: '#333333',
        labelStyle: 'uppercase',
        valueFontWeight: 'light',
        valueSizeMultiplier: 1.7,
        labelSizeMultiplier: 0.42,
        labelLetterSpacing: 0.2,
        accentColor: '#ef4444',
    },
};
