import type { TemplateDefinition } from './types';

export const dataBlockTemplate: TemplateDefinition = {
    id: 'data-block',
    metadata: {
        id: 'data-block',
        name: 'Data Block',
        description: 'Exact reference replica: PACE/min/km gray+orange, values stacked, HR 138 large',
        previewColors: { bg: '#1a1a1a', accent: '#f97316', text: '#f3f4f6' },
    },
    config: {
        templateId: 'data-block',
        layoutMode: 'data-block',
        position: 'bottom-right',
        backgroundOpacity: 0,
        fontSizePercent: 2.0,
        showHr: true,
        showPace: true,
        showDistance: true,
        showTime: false,
        fontFamily: '"Space Grotesk", Inter, -apple-system, sans-serif',
        textColor: '#FFFFFF',
        backgroundColor: 'transparent',
        borderWidth: 0,
        borderColor: 'transparent',
        cornerRadius: 0,
        textShadow: true,
        textShadowColor: 'rgba(0,0,0,0.6)',
        textShadowBlur: 10,
        lineSpacing: 1.0,
        layout: 'vertical',
        iconStyle: 'none',
        gradientBackground: false,
        gradientStartColor: '#000000',
        gradientEndColor: '#000000',
        labelStyle: 'uppercase',
        valueFontWeight: 'light',
        valueSizeMultiplier: 2.2,
        labelSizeMultiplier: 0.38,
        labelLetterSpacing: 0.2,
        accentColor: '#f97316',
    },
};
