import { DEFAULT_CAPABILITIES, defineTemplate } from './types';

export const dataBlockTemplate = defineTemplate({
  id: 'data-block',
  metadata: {
    name: 'Data Block',
    description: 'A compact HR-led telemetry block with aligned supporting metrics',
    previewColors: { bg: '#111821', accent: '#f97316', text: '#f8fafc' },
  },
  config: {
    layoutMode: 'data-block',
    position: 'bottom-right',
    backgroundOpacity: 0,
    fontSizePercent: 2.2,
    showHr: true,
    showPace: true,
    showDistance: true,
    showTime: false,
    fontFamily: 'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    textColor: '#f8fafc',
    backgroundColor: 'transparent',
    textShadow: false,
    textShadowColor: 'transparent',
    textShadowBlur: 0,
    lineSpacing: 1.15,
    layout: 'vertical',
    labelStyle: 'uppercase',
    valueFontWeight: 'bold',
    valueSizeMultiplier: 1.4,
    labelSizeMultiplier: 0.48,
    labelLetterSpacing: 0.06,
    accentColor: '#f97316',
  },
  capabilities: {
    ...DEFAULT_CAPABILITIES,
    supportedMetrics: ['pace', 'hr', 'distance', 'time', 'power'],
    supportsPosition: false,
    supportsBackgroundOpacity: false,
    supportsGradient: false,
    supportsBorder: false,
    supportsTextShadow: false,
    supportsLayoutDirection: false,
  },
  styles: {
    typography: {
      fontFamily: 'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      valueFontWeight: 'bold',
      labelFontWeight: 'normal',
      valueSizeMultiplier: 1.4,
      labelSizeMultiplier: 0.48,
      labelLetterSpacing: 0.06,
    },
    spacing: {
      basePaddingPercent: 0.025,
      metricGapPercent: 0.014,
      lineSpacing: 1.15,
    },
    visual: {
      textShadow: false,
      textShadowBlur: 0,
      labelStyle: 'uppercase',
    },
  },
});
