import type { TemplateDefinition } from './types';

export const editorialTemplate: TemplateDefinition = {
    id: 'editorial',
    metadata: {
        id: 'editorial',
        name: 'Editorial',
        description: 'Magazine-inspired serif hero pace with small side stats',
        previewColors: { bg: '#121212', accent: '#d1d5db', text: '#f8fafc' },
    },
    config: {
        templateId: 'editorial',
        layoutMode: 'editorial',
        position: 'bottom-left',
        backgroundOpacity: 0,
        fontSizePercent: 2.1,
        showHr: true,
        showPace: true,
        showDistance: true,
        showTime: true,
        fontFamily: '"Georgia", "Times New Roman", serif',
        textColor: '#FFFFFF',
        backgroundColor: 'transparent',
        borderWidth: 0,
        borderColor: 'transparent',
        cornerRadius: 0,
        textShadow: true,
        textShadowColor: 'rgba(0,0,0,0.35)',
        textShadowBlur: 3,
        lineSpacing: 1.1,
        layout: 'vertical',
        iconStyle: 'none',
        gradientBackground: false,
        gradientStartColor: '#000000',
        gradientEndColor: '#333333',
        labelStyle: 'uppercase',
        valueFontWeight: 'normal',
        valueSizeMultiplier: 2.2,
        labelSizeMultiplier: 0.34,
        labelLetterSpacing: 0.2,
        accentColor: '#e5e7eb',
    },
};
