import type { TemplateDefinition } from './types';

export const floatingPillsTemplate: TemplateDefinition = {
    id: 'floating-pills',
    metadata: {
        id: 'floating-pills',
        name: 'Floating Pills',
        description: 'Floating glass-like pills centered at the bottom',
        previewColors: { bg: '#131a2a', accent: '#a5b4fc', text: '#ffffff' },
    },
    config: {
        templateId: 'floating-pills',
        layoutMode: 'floating-pills',
        position: 'bottom-left',
        backgroundOpacity: 0.2,
        fontSizePercent: 2.1,
        showHr: true,
        showPace: true,
        showDistance: true,
        showTime: true,
        fontFamily: 'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
        textColor: '#FFFFFF',
        backgroundColor: 'rgba(255,255,255,0.15)',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.2)',
        cornerRadius: 50,
        textShadow: false,
        textShadowColor: '#000000',
        textShadowBlur: 0,
        lineSpacing: 1.2,
        layout: 'horizontal',
        iconStyle: 'none',
        gradientBackground: false,
        gradientStartColor: '#000000',
        gradientEndColor: '#333333',
        labelStyle: 'uppercase',
        valueFontWeight: 'normal',
        valueSizeMultiplier: 1.1,
        labelSizeMultiplier: 0.45,
        labelLetterSpacing: 0.12,
        accentColor: '#a5b4fc',
    },
};
