import { DEFAULT_CAPABILITIES, defineTemplate } from './types';

export const focusTypeTemplate = defineTemplate({
  id: 'focus-type',
  metadata: {
    name: 'Focus Type',
    description: 'Editorial hero pace with refined secondary metric row and graceful fallback when pace is hidden',
    previewColors: { bg: '#030303', accent: '#FFFFFF', text: '#FFFFFF' },
  },
  config: {
    layoutMode: 'focus-type',
    position: 'bottom-left',
    backgroundOpacity: 0,
    fontSizePercent: 2.2,
    showHr: true,
    showPace: true,
    showDistance: true,
    showTime: true,
    fontFamily: '"Instrument Serif", "Iowan Old Style", Georgia, serif',
    textColor: '#FFFFFF',
    backgroundColor: 'transparent',
    borderWidth: 0,
    borderColor: 'transparent',
    cornerRadius: 0,
    textShadow: true,
    textShadowColor: 'rgba(0,0,0,0.5)',
    textShadowBlur: 24,
    lineSpacing: 1.0,
    layout: 'vertical',
    iconStyle: 'none',
    gradientBackground: false,
    gradientStartColor: '#000000',
    gradientEndColor: '#000000',
    labelStyle: 'uppercase',
    valueFontWeight: 'bold',
    valueSizeMultiplier: 2.35,
    labelSizeMultiplier: 0.32,
    labelLetterSpacing: 0.32,
    accentColor: '#FFFFFF',
  },
  capabilities: {
    ...DEFAULT_CAPABILITIES,
    supportedMetrics: ['pace', 'hr', 'distance', 'time'],
    requiredMetrics: [],
    supportsPosition: false,
    supportsBackgroundOpacity: true,
    supportsGradient: false,
    supportsBorder: false,
    supportsTextShadow: true,
    supportsAccentColor: true,
    supportsLayoutDirection: false,
  },
  styles: {
    typography: {
      fontFamily: 'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      valueFontWeight: 'normal',
      labelFontWeight: 'normal',
      valueSizeMultiplier: 2.0,
      labelSizeMultiplier: 0.4,
      labelLetterSpacing: 0.1,
    },
    spacing: {
      basePaddingPercent: 0.02,
      metricGapPercent: 0.01,
      lineSpacing: 1.2,
    },
    visual: {
      cornerRadius: 0,
      borderWidth: 0,
      textShadow: false,
      textShadowBlur: 0,
      iconStyle: 'none',
      labelStyle: 'uppercase',
    },
  },
});
