import type { TemplateDefinition } from './types';

export const focusTypeTemplate: TemplateDefinition = {
    id: 'focus-type',
    metadata: {
        id: 'focus-type',
        name: 'Focus Type',
        description: 'One massive italic serif number for pace, minor metrics small below',
        previewColors: { bg: '#030303', accent: '#FFFFFF', text: '#FFFFFF' },
    },
    config: {
        templateId: 'focus-type',
        layoutMode: 'focus-type',
        position: 'bottom-left',
        backgroundOpacity: 0,
        fontSizePercent: 2.2,
        showHr: true,
        showPace: true,
        showDistance: true,
        showTime: true,
        fontFamily: '"Instrument Serif", Georgia, serif',
        textColor: '#FFFFFF',
        backgroundColor: 'transparent',
        borderWidth: 0,
        borderColor: 'transparent',
        cornerRadius: 0,
        textShadow: true,
        textShadowColor: 'rgba(0,0,0,0.5)',
        textShadowBlur: 30,
        lineSpacing: 1.0,
        layout: 'vertical',
        iconStyle: 'none',
        gradientBackground: false,
        gradientStartColor: '#000000',
        gradientEndColor: '#000000',
        labelStyle: 'uppercase',
        valueFontWeight: 'bold',
        valueSizeMultiplier: 2.5,
        labelSizeMultiplier: 0.3,
        labelLetterSpacing: 0.5,
        accentColor: '#FFFFFF',
    },
};
