import type { TemplateDefinition } from './types';
import { DEFAULT_CAPABILITIES } from './types';

export const garminStyleTemplate: TemplateDefinition = {
    id: 'garmin-style',
    metadata: {
        id: 'garmin-style',
        name: 'Garmin Style',
        description: 'Circular arc HR gauge bottom-left + stacked orange-unit metrics on the right',
        previewColors: { bg: '#111827', accent: '#f97316', text: '#f3f4f6' },
    },
    config: {
        templateId: 'garmin-style',
        layoutMode: 'garmin-style',
        position: 'bottom-left',
        backgroundOpacity: 0,
        fontSizePercent: 2.2,
        showHr: true,
        showPace: true,
        showDistance: true,
        showTime: true,
        fontFamily: '"Space Grotesk", Inter, -apple-system, sans-serif',
        textColor: '#FFFFFF',
        backgroundColor: 'transparent',
        borderWidth: 0,
        borderColor: 'transparent',
        cornerRadius: 0,
        textShadow: true,
        textShadowColor: 'rgba(0,0,0,0.5)',
        textShadowBlur: 8,
        lineSpacing: 1.1,
        layout: 'horizontal',
        iconStyle: 'none',
        gradientBackground: false,
        gradientStartColor: '#000000',
        gradientEndColor: '#111827',
        labelStyle: 'uppercase',
        valueFontWeight: 'light',
        valueSizeMultiplier: 1.8,
        labelSizeMultiplier: 0.4,
        labelLetterSpacing: 0.18,
        accentColor: '#f97316',
    },
  capabilities: {
    ...DEFAULT_CAPABILITIES,
    supportedMetrics: ['pace', 'hr', 'distance', 'time'],
    requiredMetrics: [],
    supportsPosition: false,
    supportsBackgroundOpacity: true,
    supportsGradient: false,
    supportsBorder: false,
    supportsTextShadow: true,
    supportsAccentColor: true,
    supportsLayoutDirection: false,
  },
  styles: {
    typography: {
      fontFamily: 'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      valueFontWeight: 'normal',
      labelFontWeight: 'normal',
      valueSizeMultiplier: 2.0,
      labelSizeMultiplier: 0.4,
      labelLetterSpacing: 0.1,
    },
    spacing: {
      basePaddingPercent: 0.02,
      metricGapPercent: 0.01,
      lineSpacing: 1.2,
    },
    visual: {
      cornerRadius: 0,
      borderWidth: 0,
      textShadow: false,
      textShadowBlur: 0,
      iconStyle: 'none',
      labelStyle: 'uppercase',
    },
  },
};
