import { DEFAULT_CAPABILITIES, defineTemplate } from './types';

export const glassPanelTemplate = defineTemplate({
  id: 'glass-panel',
  metadata: {
    name: 'Glass Panel',
    description: 'A compact translucent panel with clear, evenly aligned activity metrics',
    previewColors: { bg: '#101820', accent: '#8fd3ff', text: '#f7fbff' },
  },
  config: {
    layoutMode: 'glass-panel',
    position: 'bottom-left',
    backgroundOpacity: 0.68,
    fontSizePercent: 2.2,
    fontFamily: 'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    textColor: '#f7fbff',
    backgroundColor: 'rgba(255,255,255,0.2)',
    borderWidth: 1,
    borderColor: 'rgba(230,243,255,0.65)',
    cornerRadius: 18,
    lineSpacing: 1.15,
    layout: 'horizontal',
    labelStyle: 'uppercase',
    valueFontWeight: 'bold',
    valueSizeMultiplier: 1.5,
    labelSizeMultiplier: 0.48,
    labelLetterSpacing: 0.06,
    accentColor: '#8fd3ff',
    textShadow: false,
  },
  capabilities: {
    ...DEFAULT_CAPABILITIES,
    supportedMetrics: ['pace', 'hr', 'distance', 'time', 'power'],
    supportsPosition: false,
    supportsGradient: false,
    supportsBorder: true,
    supportsTextShadow: false,
    supportsLayoutDirection: false,
  },
  styles: {
    typography: {
      fontFamily: 'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      valueFontWeight: 'bold',
      labelFontWeight: 'normal',
      valueSizeMultiplier: 1.5,
      labelSizeMultiplier: 0.48,
      labelLetterSpacing: 0.06,
    },
    spacing: {
      basePaddingPercent: 0.028,
      metricGapPercent: 0.018,
      lineSpacing: 1.15,
    },
    visual: {
      cornerRadius: 18,
      borderWidth: 1,
      textShadow: false,
      textShadowBlur: 0,
      labelStyle: 'uppercase',
    },
  },
});
