import type { TemplateDefinition } from './types';
import { DEFAULT_CAPABILITIES } from './types';

export const glassPanelTemplate: TemplateDefinition = {
    id: 'glass-panel',
    metadata: {
        id: 'glass-panel',
        name: 'Glass Panel',
        description: 'Centered floating glassmorphism card with clean metrics',
        previewColors: { bg: '#1a2035', accent: '#60a5fa', text: '#f3f4f6' },
    },
    config: {
        templateId: 'glass-panel',
        layoutMode: 'glass-panel',
        position: 'bottom-left',
        backgroundOpacity: 0.12,
        fontSizePercent: 2.0,
        showHr: true,
        showPace: true,
        showDistance: true,
        showTime: true,
        fontFamily: '"DM Sans", Inter, -apple-system, sans-serif',
        textColor: '#FFFFFF',
        backgroundColor: 'rgba(255,255,255,0.1)',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.2)',
        cornerRadius: 24,
        textShadow: false,
        textShadowColor: 'rgba(0,0,0,0.3)',
        textShadowBlur: 0,
        lineSpacing: 1.0,
        layout: 'horizontal',
        iconStyle: 'none',
        gradientBackground: false,
        gradientStartColor: '#000000',
        gradientEndColor: '#000000',
        labelStyle: 'uppercase',
        valueFontWeight: 'bold' as const,
        valueSizeMultiplier: 1.5,
        labelSizeMultiplier: 0.36,
        labelLetterSpacing: 0.22,
        accentColor: '#60a5fa',
    },
  capabilities: {
    ...DEFAULT_CAPABILITIES,
    supportedMetrics: ['pace', 'hr', 'distance', 'time'],
    requiredMetrics: [],
    supportsPosition: false,
    supportsBackgroundOpacity: true,
    supportsGradient: false,
    supportsBorder: false,
    supportsTextShadow: true,
    supportsAccentColor: true,
    supportsLayoutDirection: false,
  },
  styles: {
    typography: {
      fontFamily: 'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      valueFontWeight: 'normal',
      labelFontWeight: 'normal',
      valueSizeMultiplier: 2.0,
      labelSizeMultiplier: 0.4,
      labelLetterSpacing: 0.1,
    },
    spacing: {
      basePaddingPercent: 0.02,
      metricGapPercent: 0.01,
      lineSpacing: 1.2,
    },
    visual: {
      cornerRadius: 0,
      borderWidth: 0,
      textShadow: false,
      textShadowBlur: 0,
      iconStyle: 'none',
      labelStyle: 'uppercase',
    },
  },
};
