import type { TemplateDefinition } from './types';

export const glassPanelTemplate: TemplateDefinition = {
    id: 'glass-panel',
    metadata: {
        id: 'glass-panel',
        name: 'Glass Panel',
        description: 'Centered floating glassmorphism card with clean metrics',
        previewColors: { bg: '#1a2035', accent: '#60a5fa', text: '#f3f4f6' },
    },
    config: {
        templateId: 'glass-panel',
        layoutMode: 'glass-panel',
        position: 'bottom-left',
        backgroundOpacity: 0.12,
        fontSizePercent: 2.0,
        showHr: true,
        showPace: true,
        showDistance: true,
        showTime: true,
        fontFamily: '"DM Sans", Inter, -apple-system, sans-serif',
        textColor: '#FFFFFF',
        backgroundColor: 'rgba(255,255,255,0.1)',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.2)',
        cornerRadius: 24,
        textShadow: false,
        textShadowColor: 'rgba(0,0,0,0.3)',
        textShadowBlur: 0,
        lineSpacing: 1.0,
        layout: 'horizontal',
        iconStyle: 'none',
        gradientBackground: false,
        gradientStartColor: '#000000',
        gradientEndColor: '#000000',
        labelStyle: 'uppercase',
        valueFontWeight: 'bold' as const,
        valueSizeMultiplier: 1.5,
        labelSizeMultiplier: 0.36,
        labelLetterSpacing: 0.22,
        accentColor: '#60a5fa',
    },
};
