import type { TemplateDefinition } from './types';

export const heroNumberTemplate: TemplateDefinition = {
    id: 'hero-number',
    metadata: {
        id: 'hero-number',
        name: 'Hero Number',
        description: 'Large pace number with compact secondary metrics',
        previewColors: { bg: '#111827', accent: '#f8fafc', text: '#ffffff' },
    },
    config: {
        templateId: 'hero-number',
        layoutMode: 'hero-number',
        position: 'top-left',
        backgroundOpacity: 0,
        fontSizePercent: 2.3,
        showHr: true,
        showPace: true,
        showDistance: true,
        showTime: true,
        fontFamily: 'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
        textColor: '#FFFFFF',
        backgroundColor: 'transparent',
        borderWidth: 0,
        borderColor: 'transparent',
        cornerRadius: 0,
        textShadow: true,
        textShadowColor: 'rgba(0,0,0,0.5)',
        textShadowBlur: 14,
        lineSpacing: 1.1,
        layout: 'horizontal',
        iconStyle: 'none',
        gradientBackground: false,
        gradientStartColor: '#000000',
        gradientEndColor: '#333333',
        labelStyle: 'uppercase',
        valueFontWeight: 'bold',
        valueSizeMultiplier: 2.8,
        labelSizeMultiplier: 0.5,
        labelLetterSpacing: 0.25,
        accentColor: '#FFFFFF',
    },
};
