import type { TemplateDefinition } from './types';

export const minimalRingTemplate: TemplateDefinition = {
    id: 'minimal-ring',
    metadata: {
        id: 'minimal-ring',
        name: 'Minimal Ring',
        description: 'Thin, elegant circular progress ring for pace, bottom-right',
        previewColors: { bg: '#050505', accent: '#FFFFFF', text: '#FFFFFF' },
    },
    config: {
        templateId: 'minimal-ring',
        layoutMode: 'minimal-ring',
        position: 'bottom-right',
        backgroundOpacity: 0,
        fontSizePercent: 2.0,
        showHr: true,
        showPace: true,
        showDistance: true,
        showTime: false,
        fontFamily: '"Outfit", Inter, -apple-system, sans-serif',
        textColor: '#FFFFFF',
        backgroundColor: 'transparent',
        borderWidth: 0,
        borderColor: 'transparent',
        cornerRadius: 0,
        textShadow: false,
        textShadowColor: 'rgba(0,0,0,0.3)',
        textShadowBlur: 0,
        lineSpacing: 1.0,
        layout: 'vertical',
        iconStyle: 'none',
        gradientBackground: false,
        gradientStartColor: '#000000',
        gradientEndColor: '#000000',
        labelStyle: 'uppercase',
        valueFontWeight: 'light',
        valueSizeMultiplier: 1.6,
        labelSizeMultiplier: 0.32,
        labelLetterSpacing: 0.25,
        accentColor: '#FFFFFF',
    },
};
