import { DEFAULT_CAPABILITIES, defineTemplate } from './types';

export const nightRunnerTemplate = defineTemplate({
  id: 'night-runner',
  metadata: {
    name: 'Night Runner',
    description: 'Amber pace typography with clear, unobstructed supporting telemetry',
    previewColors: { bg: '#071016', accent: '#fbbf24', text: '#f8fafc' },
  },
  config: {
    layoutMode: 'night-runner',
    position: 'top-left',
    backgroundOpacity: 0,
    fontSizePercent: 3.2,
    fontFamily: '"DM Sans", Inter, -apple-system, sans-serif',
    textColor: '#f8fafc',
    backgroundColor: 'transparent',
    textShadow: false,
    textShadowColor: 'transparent',
    textShadowBlur: 0,
    lineSpacing: 1.15,
    layout: 'horizontal',
    labelStyle: 'uppercase',
    valueFontWeight: 'normal',
    valueSizeMultiplier: 1.9,
    labelSizeMultiplier: 0.68,
    labelLetterSpacing: 0.1,
    accentColor: '#fbbf24',
  },
  capabilities: {
    ...DEFAULT_CAPABILITIES,
    supportedMetrics: ['pace', 'hr', 'distance', 'time', 'power'],
    supportsPosition: false,
    supportsGradient: false,
    supportsBorder: false,
    supportsBackgroundOpacity: false,
    supportsTextShadow: false,
    supportsLayoutDirection: false,
  },
  styles: {
    typography: {
      fontFamily: '"DM Sans", Inter, -apple-system, sans-serif',
      valueFontWeight: 'normal',
      labelFontWeight: 'normal',
      valueSizeMultiplier: 1.9,
      labelSizeMultiplier: 0.68,
      labelLetterSpacing: 0.1,
    },
    spacing: {
      basePaddingPercent: 0.025,
      metricGapPercent: 0.018,
      lineSpacing: 1.15,
    },
    visual: {
      textShadow: false,
      textShadowBlur: 0,
      labelStyle: 'uppercase',
    },
  },
});
