import type { TemplateDefinition } from './types';

export const nightRunnerTemplate: TemplateDefinition = {
    id: 'night-runner',
    metadata: {
        id: 'night-runner',
        name: 'Night Runner',
        description: 'Amber-glow pace top center + gradient strip with three color-glowing metrics at bottom',
        previewColors: { bg: '#050505', accent: '#fbbf24', text: '#fde68a' },
    },
    config: {
        templateId: 'night-runner',
        layoutMode: 'night-runner',
        position: 'top-left',
        backgroundOpacity: 0,
        fontSizePercent: 2.4,
        showHr: true,
        showPace: true,
        showDistance: true,
        showTime: true,
        fontFamily: '"DM Sans", Inter, -apple-system, sans-serif',
        textColor: '#FFFFFF',
        backgroundColor: 'transparent',
        borderWidth: 0,
        borderColor: 'transparent',
        cornerRadius: 0,
        textShadow: true,
        textShadowColor: 'rgba(251,191,36,0.35)',
        textShadowBlur: 20,
        lineSpacing: 1.1,
        layout: 'horizontal',
        iconStyle: 'none',
        gradientBackground: false,
        gradientStartColor: '#000000',
        gradientEndColor: '#000000',
        labelStyle: 'uppercase',
        valueFontWeight: 'light',
        valueSizeMultiplier: 1.9,
        labelSizeMultiplier: 0.35,
        labelLetterSpacing: 0.3,
        accentColor: '#fbbf24',
    },
};
