import type { TemplateDefinition } from './types';

export const orangePulseTemplate: TemplateDefinition = {
    id: 'orange-pulse',
    metadata: {
        id: 'orange-pulse',
        name: 'Orange Pulse',
        description: 'Dark side panel with orange accent on pace + large glowing HR on right',
        previewColors: { bg: '#0f0f0f', accent: '#f97316', text: '#ffffff' },
    },
    config: {
        templateId: 'orange-pulse',
        layoutMode: 'orange-pulse',
        position: 'bottom-left',
        backgroundOpacity: 0,
        fontSizePercent: 2.2,
        showHr: true,
        showPace: true,
        showDistance: true,
        showTime: true,
        fontFamily: '"Outfit", Inter, -apple-system, sans-serif',
        textColor: '#FFFFFF',
        backgroundColor: 'rgba(0,0,0,0.72)',
        borderWidth: 0,
        borderColor: 'transparent',
        cornerRadius: 0,
        textShadow: false,
        textShadowColor: 'rgba(0,0,0,0.4)',
        textShadowBlur: 0,
        lineSpacing: 1.1,
        layout: 'horizontal',
        iconStyle: 'none',
        gradientBackground: false,
        gradientStartColor: '#000000',
        gradientEndColor: '#000000',
        labelStyle: 'uppercase',
        valueFontWeight: 'light',
        valueSizeMultiplier: 1.8,
        labelSizeMultiplier: 0.37,
        labelLetterSpacing: 0.22,
        accentColor: '#f97316',
    },
};
