import type { TemplateDefinition } from './types';
import { DEFAULT_CAPABILITIES } from './types';

export const raceTagTemplate: TemplateDefinition = {
    id: 'race-tag',
    metadata: {
        id: 'race-tag',
        name: 'Race Tag',
        description: 'White bib-number tag top-left with clip-path + dark bottom strip in Bebas Neue style',
        previewColors: { bg: '#ffffff', accent: '#000000', text: '#111111' },
    },
    config: {
        templateId: 'race-tag',
        layoutMode: 'race-tag',
        position: 'top-left',
        backgroundOpacity: 1.0,
        fontSizePercent: 2.0,
        showHr: true,
        showPace: true,
        showDistance: true,
        showTime: true,
        fontFamily: '"Bebas Neue", "Impact", "Arial Narrow", sans-serif',
        textColor: '#000000',
        backgroundColor: '#FFFFFF',
        borderWidth: 0,
        borderColor: 'transparent',
        cornerRadius: 0,
        textShadow: false,
        textShadowColor: 'rgba(0,0,0,0.3)',
        textShadowBlur: 0,
        lineSpacing: 1.0,
        layout: 'horizontal',
        iconStyle: 'none',
        gradientBackground: false,
        gradientStartColor: '#ffffff',
        gradientEndColor: '#ffffff',
        labelStyle: 'uppercase',
        valueFontWeight: 'normal',
        valueSizeMultiplier: 2.0,
        labelSizeMultiplier: 0.35,
        labelLetterSpacing: 0.22,
        accentColor: '#000000',
    },
  capabilities: {
    ...DEFAULT_CAPABILITIES,
    supportedMetrics: ['pace', 'hr', 'distance', 'time'],
    requiredMetrics: [],
    supportsPosition: false,
    supportsBackgroundOpacity: true,
    supportsGradient: false,
    supportsBorder: false,
    supportsTextShadow: true,
    supportsAccentColor: true,
    supportsLayoutDirection: false,
  },
  styles: {
    typography: {
      fontFamily: 'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      valueFontWeight: 'normal',
      labelFontWeight: 'normal',
      valueSizeMultiplier: 2.0,
      labelSizeMultiplier: 0.4,
      labelLetterSpacing: 0.1,
    },
    spacing: {
      basePaddingPercent: 0.02,
      metricGapPercent: 0.01,
      lineSpacing: 1.2,
    },
    visual: {
      cornerRadius: 0,
      borderWidth: 0,
      textShadow: false,
      textShadowBlur: 0,
      iconStyle: 'none',
      labelStyle: 'uppercase',
    },
  },
};
