import type { TemplateDefinition } from './types';

export const softRoundedTemplate: TemplateDefinition = {
    id: 'soft-rounded',
    metadata: {
        id: 'soft-rounded',
        name: 'Soft Rounded',
        description: 'Rounded soft cards with gentle contrast',
        previewColors: { bg: '#f8fafc', accent: '#fb7185', text: '#111827' },
    },
    config: {
        templateId: 'soft-rounded',
        layoutMode: 'soft-rounded',
        position: 'bottom-left',
        backgroundOpacity: 0.9,
        fontSizePercent: 1.95,
        showHr: true,
        showPace: true,
        showDistance: true,
        showTime: true,
        fontFamily: 'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
        textColor: '#111827',
        backgroundColor: 'rgba(255,255,255,0.92)',
        borderWidth: 0,
        borderColor: 'transparent',
        cornerRadius: 20,
        textShadow: false,
        textShadowColor: '#000000',
        textShadowBlur: 0,
        lineSpacing: 1.1,
        layout: 'horizontal',
        iconStyle: 'none',
        gradientBackground: false,
        gradientStartColor: '#ffffff',
        gradientEndColor: '#ffffff',
        labelStyle: 'uppercase',
        valueFontWeight: 'normal',
        valueSizeMultiplier: 1.1,
        labelSizeMultiplier: 0.42,
        labelLetterSpacing: 0.1,
        accentColor: '#fb7185',
    },
};
