import type { TemplateDefinition } from './types';

export const splitEdgesTemplate: TemplateDefinition = {
    id: 'split-edges',
    metadata: {
        id: 'split-edges',
        name: 'Split Edges',
        description: 'Metrics split across video corners with center marker',
        previewColors: { bg: '#0f172a', accent: '#ef4444', text: '#f1f5f9' },
    },
    config: {
        templateId: 'split-edges',
        layoutMode: 'split-edges',
        position: 'top-left',
        backgroundOpacity: 0.1,
        fontSizePercent: 2.0,
        showHr: true,
        showPace: true,
        showDistance: true,
        showTime: true,
        fontFamily: 'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
        textColor: '#FFFFFF',
        backgroundColor: 'rgba(255,255,255,0.05)',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.1)',
        cornerRadius: 8,
        textShadow: true,
        textShadowColor: 'rgba(0,0,0,0.45)',
        textShadowBlur: 6,
        lineSpacing: 1.2,
        layout: 'vertical',
        iconStyle: 'none',
        gradientBackground: false,
        gradientStartColor: '#000000',
        gradientEndColor: '#333333',
        labelStyle: 'uppercase',
        valueFontWeight: 'light',
        valueSizeMultiplier: 1.8,
        labelSizeMultiplier: 0.42,
        labelLetterSpacing: 0.18,
        accentColor: '#ef4444',
    },
};
