import { DEFAULT_CAPABILITIES, defineTemplate } from './types';

export const sportsBroadcastTemplate = defineTemplate({
  id: 'sports-broadcast',
  metadata: {
    name: 'Sports Broadcast',
    description: 'A broadcast lower third with a clean runner marker and compact metric columns',
    previewColors: { bg: '#000000', accent: '#f97316', text: '#ffffff' },
  },
  config: {
    layoutMode: 'sports-broadcast',
    position: 'bottom-left',
    backgroundOpacity: 0.9,
    fontSizePercent: 2.0,
    fontFamily: 'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    textColor: '#FFFFFF',
    backgroundColor: '#0b1118',
    textShadow: true,
    textShadowColor: 'rgba(0,0,0,0.82)',
    textShadowBlur: 2,
    lineSpacing: 1.2,
    layout: 'horizontal',
    labelStyle: 'uppercase',
    valueFontWeight: 'bold',
    valueSizeMultiplier: 1.5,
    labelSizeMultiplier: 0.46,
    labelLetterSpacing: 0.08,
    accentColor: '#f97316',
  },
  capabilities: {
    ...DEFAULT_CAPABILITIES,
    supportedMetrics: ['pace', 'hr', 'distance', 'time', 'power'],
    supportsPosition: false,
    supportsBackgroundOpacity: true,
    supportsGradient: false,
    supportsBorder: false,
    supportsTextShadow: true,
    supportsLayoutDirection: false,
  },
  styles: {
    typography: {
      fontFamily: 'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      valueFontWeight: 'bold',
      labelFontWeight: 'normal',
      valueSizeMultiplier: 1.5,
      labelSizeMultiplier: 0.46,
      labelLetterSpacing: 0.08,
    },
    spacing: {
      basePaddingPercent: 0.03,
      metricGapPercent: 0.015,
      lineSpacing: 1.2,
    },
    visual: {
      textShadow: true,
      textShadowBlur: 2,
      labelStyle: 'uppercase',
    },
  },
});
