import type { TemplateDefinition } from './types';

export const sportsBroadcastTemplate: TemplateDefinition = {
    id: 'sports-broadcast',
    metadata: {
        id: 'sports-broadcast',
        name: 'Sports Broadcast',
        description: 'TV lower-third: orange accent line + RUN label, orange metric labels, large values',
        previewColors: { bg: '#000000', accent: '#f97316', text: '#ffffff' },
    },
    config: {
        templateId: 'sports-broadcast',
        layoutMode: 'sports-broadcast',
        position: 'bottom-left',
        backgroundOpacity: 0.88,
        fontSizePercent: 2.0,
        showHr: true,
        showPace: true,
        showDistance: true,
        showTime: true,
        fontFamily: '"Space Grotesk", Inter, -apple-system, sans-serif',
        textColor: '#FFFFFF',
        backgroundColor: 'rgba(0,0,0,0.88)',
        borderWidth: 0,
        borderColor: 'transparent',
        cornerRadius: 0,
        textShadow: false,
        textShadowColor: 'rgba(0,0,0,0.5)',
        textShadowBlur: 0,
        lineSpacing: 1.0,
        layout: 'horizontal',
        iconStyle: 'none',
        gradientBackground: false,
        gradientStartColor: '#000000',
        gradientEndColor: '#000000',
        labelStyle: 'uppercase',
        valueFontWeight: 'light',
        valueSizeMultiplier: 1.6,
        labelSizeMultiplier: 0.38,
        labelLetterSpacing: 0.2,
        accentColor: '#f97316',
    },
};
