import type { TemplateDefinition } from './types';

export const stackedSerifTemplate: TemplateDefinition = {
    id: 'stacked-serif',
    metadata: {
        id: 'stacked-serif',
        name: 'Stacked Serif',
        description: 'Vertical serif stack with understated labels',
        previewColors: { bg: '#111111', accent: '#d4d4d8', text: '#ffffff' },
    },
    config: {
        templateId: 'stacked-serif',
        layoutMode: 'stacked-serif',
        position: 'bottom-left',
        backgroundOpacity: 0,
        fontSizePercent: 2.0,
        showHr: true,
        showPace: true,
        showDistance: true,
        showTime: true,
        fontFamily: '"Georgia", "Times New Roman", serif',
        textColor: '#FFFFFF',
        backgroundColor: 'transparent',
        borderWidth: 0,
        borderColor: 'transparent',
        cornerRadius: 0,
        textShadow: true,
        textShadowColor: 'rgba(0,0,0,0.45)',
        textShadowBlur: 4,
        lineSpacing: 1.1,
        layout: 'vertical',
        iconStyle: 'none',
        gradientBackground: false,
        gradientStartColor: '#000000',
        gradientEndColor: '#333333',
        labelStyle: 'hidden',
        valueFontWeight: 'normal',
        valueSizeMultiplier: 1.7,
        labelSizeMultiplier: 0.38,
        labelLetterSpacing: 0.12,
        accentColor: '#e5e7eb',
    },
};
