import type { TemplateDefinition } from './types';
import { DEFAULT_CAPABILITIES } from './types';

export const stretchedBarTemplate: TemplateDefinition = {
    id: 'stretched-bar',
    metadata: {
        id: 'stretched-bar',
        name: 'Stretched Bar',
        description: 'Full-width top bar with widely spaced monospace metrics',
        previewColors: { bg: '#000000', accent: '#FFFFFF', text: '#FFFFFF' },
    },
    config: {
        templateId: 'stretched-bar',
        layoutMode: 'stretched-bar',
        position: 'top-left',
        backgroundOpacity: 0,
        fontSizePercent: 2.2,
        showHr: true,
        showPace: true,
        showDistance: true,
        showTime: true,
        fontFamily: '"JetBrains Mono", "Fira Code", monospace',
        textColor: '#FFFFFF',
        backgroundColor: 'transparent',
        borderWidth: 0,
        borderColor: 'transparent',
        cornerRadius: 0,
        textShadow: false,
        textShadowColor: 'rgba(0,0,0,0.3)',
        textShadowBlur: 0,
        lineSpacing: 1.0,
        layout: 'horizontal',
        iconStyle: 'none',
        gradientBackground: false,
        gradientStartColor: '#000000',
        gradientEndColor: '#000000',
        labelStyle: 'uppercase',
        valueFontWeight: 'normal',
        valueSizeMultiplier: 1.8,
        labelSizeMultiplier: 0.35,
        labelLetterSpacing: 0.15,
        accentColor: '#FFFFFF',
    },
  capabilities: {
    ...DEFAULT_CAPABILITIES,
    supportedMetrics: ['pace', 'hr', 'distance', 'time'],
    requiredMetrics: [],
    supportsPosition: false,
    supportsBackgroundOpacity: true,
    supportsGradient: false,
    supportsBorder: false,
    supportsTextShadow: true,
    supportsAccentColor: true,
    supportsLayoutDirection: false,
  },
  styles: {
    typography: {
      fontFamily: 'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      valueFontWeight: 'normal',
      labelFontWeight: 'normal',
      valueSizeMultiplier: 2.0,
      labelSizeMultiplier: 0.4,
      labelLetterSpacing: 0.1,
    },
    spacing: {
      basePaddingPercent: 0.02,
      metricGapPercent: 0.01,
      lineSpacing: 1.2,
    },
    visual: {
      cornerRadius: 0,
      borderWidth: 0,
      textShadow: false,
      textShadowBlur: 0,
      iconStyle: 'none',
      labelStyle: 'uppercase',
    },
  },
};
