import type { TemplateDefinition } from './types';

export const swissGridTemplate: TemplateDefinition = {
    id: 'swiss-grid',
    metadata: {
        id: 'swiss-grid',
        name: 'Swiss Grid',
        description: 'Structured typographic grid in a clean bottom panel',
        previewColors: { bg: '#000000', accent: '#d1d5db', text: '#f3f4f6' },
    },
    config: {
        templateId: 'swiss-grid',
        layoutMode: 'swiss-grid',
        position: 'bottom-left',
        backgroundOpacity: 0.72,
        fontSizePercent: 1.95,
        showHr: true,
        showPace: true,
        showDistance: true,
        showTime: true,
        fontFamily: 'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
        textColor: '#FFFFFF',
        backgroundColor: 'rgba(0,0,0,0.72)',
        borderWidth: 0,
        borderColor: 'transparent',
        cornerRadius: 0,
        textShadow: false,
        textShadowColor: '#000000',
        textShadowBlur: 0,
        lineSpacing: 1.1,
        layout: 'horizontal',
        iconStyle: 'none',
        gradientBackground: false,
        gradientStartColor: '#000000',
        gradientEndColor: '#333333',
        labelStyle: 'uppercase',
        valueFontWeight: 'normal',
        valueSizeMultiplier: 1.2,
        labelSizeMultiplier: 0.38,
        labelLetterSpacing: 0.16,
        accentColor: '#d1d5db',
    },
};
