import type { TemplateDefinition } from './types';
import { DEFAULT_CAPABILITIES } from './types';

export const terminalTemplate: TemplateDefinition = {
    id: 'terminal',
    metadata: {
        id: 'terminal',
        name: 'Terminal',
        description: 'Green hacker terminal top-left: › pace = 5:30 min/km style',
        previewColors: { bg: '#000000', accent: '#22c55e', text: '#4ade80' },
    },
    config: {
        templateId: 'terminal',
        layoutMode: 'terminal',
        position: 'top-left',
        backgroundOpacity: 0.82,
        fontSizePercent: 1.8,
        showHr: true,
        showPace: true,
        showDistance: true,
        showTime: true,
        fontFamily: '"JetBrains Mono", "Fira Code", "Courier New", monospace',
        textColor: '#86efac',
        backgroundColor: 'rgba(0,0,0,0.82)',
        borderWidth: 1,
        borderColor: 'rgba(34,197,94,0.2)',
        cornerRadius: 4,
        textShadow: false,
        textShadowColor: 'rgba(0,0,0,0.4)',
        textShadowBlur: 0,
        lineSpacing: 1.2,
        layout: 'vertical',
        iconStyle: 'none',
        gradientBackground: false,
        gradientStartColor: '#000000',
        gradientEndColor: '#000000',
        labelStyle: 'uppercase',
        valueFontWeight: 'normal',
        valueSizeMultiplier: 1.0,
        labelSizeMultiplier: 0.45,
        labelLetterSpacing: 0.08,
        accentColor: '#22c55e',
    },
  capabilities: {
    ...DEFAULT_CAPABILITIES,
    supportedMetrics: ['pace', 'hr', 'distance', 'time'],
    requiredMetrics: [],
    supportsPosition: false,
    supportsBackgroundOpacity: true,
    supportsGradient: false,
    supportsBorder: false,
    supportsTextShadow: true,
    supportsAccentColor: true,
    supportsLayoutDirection: false,
  },
  styles: {
    typography: {
      fontFamily: 'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      valueFontWeight: 'normal',
      labelFontWeight: 'normal',
      valueSizeMultiplier: 2.0,
      labelSizeMultiplier: 0.4,
      labelLetterSpacing: 0.1,
    },
    spacing: {
      basePaddingPercent: 0.02,
      metricGapPercent: 0.01,
      lineSpacing: 1.2,
    },
    visual: {
      cornerRadius: 0,
      borderWidth: 0,
      textShadow: false,
      textShadowBlur: 0,
      iconStyle: 'none',
      labelStyle: 'uppercase',
    },
  },
};
