import { DEFAULT_CAPABILITIES, defineTemplate } from './types';

export const terminalTemplate = defineTemplate({
  id: 'terminal',
  metadata: {
    name: 'Terminal',
    description: 'A compact telemetry console with aligned keys, values, and units',
    previewColors: { bg: '#050907', accent: '#39d98a', text: '#e9f5ee' },
  },
  config: {
    layoutMode: 'terminal',
    position: 'top-left',
    backgroundOpacity: 0.94,
    fontSizePercent: 2,
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", monospace',
    textColor: '#e9f5ee',
    backgroundColor: '#050907',
    borderWidth: 1,
    borderColor: 'rgba(57,217,138,0.38)',
    cornerRadius: 5,
    lineSpacing: 1.2,
    layout: 'vertical',
    labelStyle: 'uppercase',
    valueFontWeight: 'bold',
    valueSizeMultiplier: 1.1,
    labelSizeMultiplier: 0.78,
    labelLetterSpacing: 0.04,
    accentColor: '#39d98a',
  },
  capabilities: {
    ...DEFAULT_CAPABILITIES,
    supportedMetrics: ['pace', 'hr', 'distance', 'time', 'power'],
    supportsPosition: false,
    supportsGradient: false,
    supportsBorder: true,
    supportsTextShadow: true,
    supportsLayoutDirection: false,
  },
  styles: {
    typography: {
      fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", monospace',
      valueFontWeight: 'bold',
      labelFontWeight: 'normal',
      valueSizeMultiplier: 1.1,
      labelSizeMultiplier: 0.78,
      labelLetterSpacing: 0.04,
    },
    spacing: {
      basePaddingPercent: 0.02,
      metricGapPercent: 0.008,
      lineSpacing: 1.2,
    },
    visual: {
      cornerRadius: 5,
      borderWidth: 1,
      textShadow: false,
      textShadowBlur: 0,
      labelStyle: 'uppercase',
    },
  },
});
