import type { TemplateDefinition } from './types';

export const thinLineTemplate: TemplateDefinition = {
  id: 'thin-line',
  metadata: {
    id: 'thin-line',
    name: 'Thin Line',
    description: 'Ultra-thin baseline and lightweight inline metrics',
    previewColors: { bg: '#0f172a', accent: '#cbd5e1', text: '#e2e8f0' },
  },
  config: {
    templateId: 'thin-line',
    layoutMode: 'thin-line',
    position: 'bottom-left',
    backgroundOpacity: 0,
    fontSizePercent: 1.55,
    showHr: true,
    showPace: true,
    showDistance: true,
    showTime: true,
    fontFamily: 'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    textColor: 'rgba(255,255,255,0.8)',
    backgroundColor: 'transparent',
    borderWidth: 0,
    borderColor: 'transparent',
    cornerRadius: 0,
    textShadow: false,
    textShadowColor: '#000000',
    textShadowBlur: 0,
    lineSpacing: 1,
    layout: 'horizontal',
    iconStyle: 'none',
    gradientBackground: false,
    gradientStartColor: '#000000',
    gradientEndColor: '#333333',
    labelStyle: 'hidden',
    valueFontWeight: 'light',
    valueSizeMultiplier: 1,
    labelSizeMultiplier: 0.3,
    labelLetterSpacing: 0.1,
    accentColor: '#cbd5e1',
  },
};
