import type { TemplateDefinition } from './types';

export const tickerTapeTemplate: TemplateDefinition = {
    id: 'ticker-tape',
    metadata: {
        id: 'ticker-tape',
        name: 'Ticker Tape',
        description: 'Live ticker strip at the bottom edge',
        previewColors: { bg: '#0a0a0a', accent: '#ef4444', text: '#f8fafc' },
    },
    config: {
        templateId: 'ticker-tape',
        layoutMode: 'ticker-tape',
        position: 'bottom-left',
        backgroundOpacity: 0.95,
        fontSizePercent: 1.7,
        showHr: true,
        showPace: true,
        showDistance: true,
        showTime: true,
        fontFamily: '"JetBrains Mono", ui-monospace, SFMono-Regular, Menlo, monospace',
        textColor: '#FFFFFF',
        backgroundColor: '#000000',
        borderWidth: 0,
        borderColor: 'transparent',
        cornerRadius: 0,
        textShadow: false,
        textShadowColor: '#000000',
        textShadowBlur: 0,
        lineSpacing: 1.2,
        layout: 'horizontal',
        iconStyle: 'none',
        gradientBackground: false,
        gradientStartColor: '#000000',
        gradientEndColor: '#333333',
        labelStyle: 'hidden',
        valueFontWeight: 'normal',
        valueSizeMultiplier: 1.0,
        labelSizeMultiplier: 0.4,
        labelLetterSpacing: 0.12,
        accentColor: '#ef4444',
    },
};
