import { DEFAULT_CAPABILITIES, defineTemplate } from './types';

export const trailRunTemplate = defineTemplate({
    id: 'trail-run',
    metadata: {
        name: 'Trail Run',
        description: 'Minimal trail HUD with a live heart-rate trace and alpine stats',
        previewColors: { bg: '#050505', accent: '#FF3B30', text: '#FFFFFF' },
    },
    config: {
        layoutMode: 'trail-run',
        position: 'top-left',
        backgroundOpacity: 0,
        fontSizePercent: 2.4,
        showHr: true,
        showPace: false,
        showDistance: false,
        showTime: false,
        showSpeed: false,
        showGrade: true,
        showElevation: true,
        showCadence: false,
        showPower: false,
        fontFamily: '"SFMono-Regular", "Roboto Mono", Menlo, monospace',
        textColor: '#FFFFFF',
        backgroundColor: 'transparent',
        borderWidth: 0,
        borderColor: 'transparent',
        cornerRadius: 0,
        textShadow: true,
        textShadowColor: 'rgba(0,0,0,0.7)',
        textShadowBlur: 4,
        lineSpacing: 1,
        layout: 'horizontal',
        iconStyle: 'none',
        gradientBackground: false,
        gradientStartColor: 'transparent',
        gradientEndColor: 'transparent',
        labelStyle: 'uppercase',
        valueFontWeight: 'light',
        valueSizeMultiplier: 2.6,
        labelSizeMultiplier: 0.32,
        labelLetterSpacing: 0.12,
        accentColor: '#FF3B30',
    },
    capabilities: {
        ...DEFAULT_CAPABILITIES,
        supportedMetrics: ['hr', 'grade', 'elevation'],
        requiredMetrics: ['hr', 'grade', 'elevation'],
        supportsPosition: false,
        supportsBackgroundOpacity: false,
        supportsGradient: false,
        supportsBorder: false,
        supportsTextShadow: true,
        supportsAccentColor: false,
        supportsLayoutDirection: false,
    },
});
