import { TRAIL_RUN_FONT_FAMILY } from '../trailRunFonts';
import { DEFAULT_CAPABILITIES, defineTemplate } from './types';

export const trailRunTemplate = defineTemplate({
    id: 'trail-run',
    metadata: {
        name: 'Trail Run',
        description: 'Minimal trail HUD with a live heart-rate trace and alpine stats',
        previewColors: { bg: '#050505', accent: '#FF3B30', text: '#FFFFFF' },
    },
    config: {
        layoutMode: 'trail-run',
        position: 'top-left',
        backgroundOpacity: 0,
        fontSizePercent: 2.4,
        showHr: true,
        showPace: true,
        showDistance: true,
        showTime: true,
        showGrade: true,
        showElevation: true,
        fontFamily: TRAIL_RUN_FONT_FAMILY,
        textColor: '#FFFFFF',
        backgroundColor: 'transparent',
        textShadow: true,
        textShadowColor: 'rgba(0,0,0,0.7)',
        textShadowBlur: 4,
        lineSpacing: 1,
        layout: 'horizontal',
        gradientStartColor: 'transparent',
        gradientEndColor: 'transparent',
        labelStyle: 'uppercase',
        valueFontWeight: 'bold',
        valueSizeMultiplier: 2.6,
        labelSizeMultiplier: 0.32,
        labelLetterSpacing: 0.12,
        accentColor: '#FF3B30',
    },
    capabilities: {
        ...DEFAULT_CAPABILITIES,
        supportedMetrics: ['pace', 'hr', 'distance', 'time', 'grade', 'elevation', 'power'],
        supportsPosition: false,
        supportsBackgroundOpacity: false,
        supportsGradient: false,
        supportsBorder: false,
        supportsAccentColor: false,
        supportsLayoutDirection: false,
    },
});
