import type { TemplateDefinition } from './types';

export const twoToneTemplate: TemplateDefinition = {
    id: 'two-tone',
    metadata: {
        id: 'two-tone',
        name: 'Two Tone',
        description: 'High-contrast split typography with accent pace',
        previewColors: { bg: '#050505', accent: '#c8ff00', text: '#f8fafc' },
    },
    config: {
        templateId: 'two-tone',
        layoutMode: 'two-tone',
        position: 'bottom-left',
        backgroundOpacity: 0,
        fontSizePercent: 2.2,
        showHr: true,
        showPace: true,
        showDistance: true,
        showTime: true,
        fontFamily: 'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
        textColor: '#FFFFFF',
        backgroundColor: 'transparent',
        borderWidth: 0,
        borderColor: 'transparent',
        cornerRadius: 0,
        textShadow: true,
        textShadowColor: 'rgba(0,0,0,0.5)',
        textShadowBlur: 8,
        lineSpacing: 1.1,
        layout: 'vertical',
        iconStyle: 'none',
        gradientBackground: false,
        gradientStartColor: '#000000',
        gradientEndColor: '#333333',
        labelStyle: 'uppercase',
        valueFontWeight: 'bold',
        valueSizeMultiplier: 2.4,
        labelSizeMultiplier: 0.36,
        labelLetterSpacing: 0.22,
        accentColor: '#c8ff00',
    },
};
