import type { TemplateDefinition } from './types';
import { DEFAULT_CAPABILITIES } from './types';

export const whisperTemplate: TemplateDefinition = {
    id: 'whisper',
    metadata: {
        id: 'whisper',
        name: 'Whisper',
        description: 'Ultra-subtle and low-contrast corner telemetry',
        previewColors: { bg: '#101218', accent: '#9ca3af', text: '#e5e7eb' },
    },
    config: {
        templateId: 'whisper',
        layoutMode: 'whisper',
        position: 'bottom-right',
        backgroundOpacity: 0,
        fontSizePercent: 1.5,
        showHr: true,
        showPace: true,
        showDistance: true,
        showTime: true,
        fontFamily: 'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
        textColor: 'rgba(255,255,255,0.28)',
        backgroundColor: 'transparent',
        borderWidth: 0,
        borderColor: 'transparent',
        cornerRadius: 0,
        textShadow: false,
        textShadowColor: '#000000',
        textShadowBlur: 0,
        lineSpacing: 1.05,
        layout: 'vertical',
        iconStyle: 'none',
        gradientBackground: false,
        gradientStartColor: '#000000',
        gradientEndColor: '#333333',
        labelStyle: 'hidden',
        valueFontWeight: 'light',
        valueSizeMultiplier: 0.95,
        labelSizeMultiplier: 0.32,
        labelLetterSpacing: 0.08,
        accentColor: '#9ca3af',
    },
  capabilities: {
    ...DEFAULT_CAPABILITIES,
    supportedMetrics: ['pace', 'hr', 'distance', 'time'],
    requiredMetrics: [],
    supportsPosition: false,
    supportsBackgroundOpacity: true,
    supportsGradient: false,
    supportsBorder: false,
    supportsTextShadow: true,
    supportsAccentColor: true,
    supportsLayoutDirection: false,
  },
  styles: {
    typography: {
      fontFamily: 'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
      valueFontWeight: 'normal',
      labelFontWeight: 'normal',
      valueSizeMultiplier: 2.0,
      labelSizeMultiplier: 0.4,
      labelLetterSpacing: 0.1,
    },
    spacing: {
      basePaddingPercent: 0.02,
      metricGapPercent: 0.01,
      lineSpacing: 1.2,
    },
    visual: {
      cornerRadius: 0,
      borderWidth: 0,
      textShadow: false,
      textShadowBlur: 0,
      iconStyle: 'none',
      labelStyle: 'uppercase',
    },
  },
};
